[package]
name = "sprid"
version = "0.5.0"
description = "A terminal emulator written in Almide"

[dependencies]
snaidhm = { git = "https://github.com/almide-graphics/snaidhm.git" }

[native-deps]
libc = "0.2"
png = "0.17"
